#!/bin/sh
# Setup a machine for Sublime Text 2
set -x

# symlink settings in
sublime_dir=~/Library/Application\ Support/Sublime\ Text\ 2/Packages
mv "$sublime_dir/User" "$sublime_dir/User.backup"
ln -s "$ZSH/sublime2/User" "$sublime_dir"

# Grab the Soda theme
cd "$sublime_dir"
git clone https://github.com/buymeasoda/soda-theme/ "Theme - Soda"

# Install Package Control
mkdir ~/Library/Application\ Support/Sublime\ Text\ 2/Installed\ Packages
curl -o ~/Library/Application\ Support/Sublime\ Text\ 2/Installed\ Packages/Package\ Control.sublime-package http://sublime.wbond.net/Package%20Control.sublime-package