#!/bin/sh
#
# Homebrew
#
# This installs some of the common dependencies needed (or at least desired)
# using Homebrew.

# Check for Homebrew
if test ! $(which brew)
then
  echo "  x You should probably install Homebrew first:"
  echo "    https://github.com/mxcl/homebrew/wiki/installation"
  exit
else
  echo "  + Homebrew found."
fi

# Install grc and coreutils
brew install grc coreutils

# OS X ships with git version 1.7.10.2 (Apple Git-33), install 1.8.x
brew install git

# Install appledoc so pods can generate documentation
brew install appledoc
